### ISSUE TITLE
Establish a basic README.md file

### ISSUE THREAD

**Issue by mgifford** [usds/ditap-curriculum-update#1]
**Dependencies**

- None

**Definition of Success**

A readme file that includes the following:
- What is DITAP 
- how people are involved 

**Open Questions**

**Additional information/notes**

- We won't have anything much for people to comment on, but with any public GitHub project, people should be welcome to submit feature requests for the work.

**Comment by farooqzakhilwal** [comment]
@vdavez would love to get your review before I put this on the public repo: https://docs.google.com/document/d/11hCQHjvQKI3M-VGz5gfltGnbGz3kHe_u3tXCQ-Tue6Y/edit?tab=t.0#heading=h.kixyqk6hsj1k

**Comment by vdavez** [comment]
@farooqzakhilwal I'd like to suggest that we hold off on publicizing the consortium work until we first speak to the existing providers. I worry that if we talk about the consortium without engaging them first, it might create resistance. Thoughts?

**Comment by vdavez** [comment]
Alternatively, if we are vague enough about the approach (I suggested edits), folks could approach the governance conversation with their own ideas and maybe that's not a bad thing?

**Comment by vdavez** [comment]
Put some suggested edits in the doc.

**Comment by farooqzakhilwal** [comment]
@frank-mcnally this is ready for your review. I'll Slack the file over to you.

**Comment by farooqzakhilwal** [comment]
Received feedback, putting this issue back in progress.

**Comment by farooqzakhilwal** [comment]
Updated based on feedback and changes shared with Frank in Slack for final approval.

**Comment by mgifford** [comment]
We can build on https://github.com/DSACMS/repo-scaffolder/tree/main
