### ISSUE TITLE
Chianti's Test Ticket

### ISSUE THREAD

**Issue by Chianti7** [usds/ditap-curriculum-update#11]
Objective

Open questions

Approach

Outcome

Additional information/notes

**Comment by april-cruz** [comment]
Hi @Chianti7, I'm testing out comments here. Can you close this issue when you get the chance? Thanks!

**Comment by Chianti7** [comment]
just seeing this. I see that the issue is closed now.


*Chianti Lomax*
CivicActions | Workplace Development
CivicActions <https://civicactions.com/>
she/her <https://www.mypronouns.org/what-and-why> ––––––––––
–––––––––––––––––
