### ISSUE TITLE
 In Class Sessions: R3 - Participant Packet 

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#126]
**Dependencies**

**Definition of success**
- This content has been fully reviewed and documented according to the rubric.

**Other information**

**Additional context**
- Content Map spreadsheet: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?usp=sharing 

- Rubric: https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing 

- [x] Curriculum design

**Comment by Chianti7** [comment]
@april-cruz this one also has the rubric for R1 instead of R3.
