### ISSUE TITLE
In Class Sessions: R1 - Participant Packet

### ISSUE THREAD

**Issue by TahiraG** [usds/ditap-curriculum-update#129]
Dependencies

Definition of success
Participant Packet:
https://docs.google.com/document/d/10WqtYfxaDfzH1yQL-fI30dKRbRxH1jQI/edit#heading=h.gjdgxs

This content has been fully reviewed and documented according to the[ [rubric]).](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?gid=1031066866#gid=1031066866)

Other information

Additional context
Content Map spreadsheet: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?usp=sharing

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Design

**Comment by teresahernandezidt** [comment]
Curriculum Design completed.

**Comment by teresahernandezidt** [comment]
Assigned for Spelling and Grammar

**Comment by teresahernandezidt** [comment]
Spelling and grammar complete

**Comment by cruzaprild** [comment]
Beginning 508 compliance audit

**Comment by cruzaprild** [comment]
508 compliance audit is complete. All other audits are complete so moving to done.
