### ISSUE TITLE
In Class Sessions: R2 - Facilitator Summary: Additional Agenda Notes

### ISSUE THREAD

**Issue by TahiraG** [usds/ditap-curriculum-update#135]
Verifier: @teresahernandezidt 

Dependencies

Definition of success
Facilitator Summary: Additional Agenda Notes: https://docs.google.com/document/u/2/d/1-EJXn_s0isGZjJZypqtUow2AsAAGkqP7/edit?usp=drive_web&ouid=104013756643397925294&rtpof=true

This content has been fully reviewed and documented according to the[ [rubric]).](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?gid=1031066866#gid=1031066866)

Other information

Additional context
Content Map spreadsheet: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?usp=sharing

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by cruzaprild** [comment]
Beginning 508 compliance audit

**Comment by teresahernandezidt** [comment]
assigning Curriculum and Spelling and Grammar audits to myself

**Comment by teresahernandezidt** [comment]
curriculum and spelling audits complete
