### ISSUE TITLE
In Class Sessions: R2 - Participant Packet 

### ISSUE THREAD

**Issue by TahiraG** [usds/ditap-curriculum-update#143]
Dependencies

Definition of success
R2 Participant Packet:
https://docs.google.com/document/u/2/d/1cjvRR-jLYhE2y20reCr6ZjorAIegMNGi/edit?usp=drive_web&ouid=104013756643397925294&rtpof=true

This content has been fully reviewed and documented according to the[ [rubric]).](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?gid=1031066866#gid=1031066866)

Other information

Additional context
Content Map spreadsheet: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?usp=sharing

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Audit

**Comment by cruzaprild** [comment]
Assigning for 508 and spelling/grammar

**Comment by cruzaprild** [comment]
508 and spelling/grammar audits complete. This tasks can move to done when you finish CD. @teresahernandezidt

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete
