### ISSUE TITLE
In Class Sessions: R4 - Facilitator Summary Additional Agenda Notes

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#150]
**Dependencies**

**Definition of success**
- This content has been fully reviewed and documented according to the rubric.

**Other information**

**Additional context**
- Mostly applied learning related

- Content Map spreadsheet: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?usp=sharing

- Rubric: https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing

- [x] Curriculum Design

**Comment by Chianti7** [comment]
Correct Rubric: https://docs.google.com/spreadsheets/d/1l5-_46-cABbltw9OD9e_P9P3MF0zRbU5Eblx5tvwHYc/edit?gid=1921496169#gid=1921496169

**Comment by Chianti7** [comment]
Curriculum audit complete
