### ISSUE TITLE
Assessments: R1 Release 1 Post-Assessment

### ISSUE THREAD

**Issue by teresahernandezidt** [usds/ditap-curriculum-update#152]
**Verifier:** @teresahernandezidt 

**Dependencies**
- 

**Definition of success**
Release 1 Week 3 Assessment:
https://docs.google.com/document/d/1Z46UFIuLys_fi5MpJkfuv-AU6mchuypO/edit

The content has been evaluated according to the Audit Process rubric.
 https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?gid=0#gid=0

**Other information**
- 

**Additional context**
Content Map spreadsheet: https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by teresahernandezidt** [comment]
Beginning Curriculum Design audit

**Comment by teresahernandezidt** [comment]
Curriculum Design audit complete.

**Comment by Chianti7** [comment]
Spelling and grammar check done.

**Comment by Chianti7** [comment]
@april-cruz  This one only has the 508 audit check left.

**Comment by cruzaprild** [comment]
Great! @Chianti7 

Beginning 508 audit check now

**Comment by cruzaprild** [comment]
All audits are complete. Moving task to done.
