### ISSUE TITLE
Self-Paced Learning: R1A - Required Readings

### ISSUE THREAD

**Issue by cruzaprild** [usds/ditap-curriculum-update#155]
**Dependencies**
- None

**Definition of success**
- "Required readings" have been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS. 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) View LMS tab for more information

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Design

**Comment by teresahernandezidt** [comment]
completed curriculum design

**Comment by Chianti7** [comment]
Assigning for spelling and grammar

**Comment by Chianti7** [comment]
Picking up for spelling and grammar

**Comment by Chianti7** [comment]
@april-cruz This might a good item for SMEs to confirm if these articles are outdated or should be replaced with newer more relevant articles.

**Comment by cruzaprild** [comment]
@Chianti7 Okay, thanks for the note. Do you think they should review all the "required readings" sections for every release? I can bundle those tickets for their review if so.

**Comment by Chianti7** [comment]
@cruzaprild Yes - anything that says required readings means that it was mandated to receive certification from USDS so if these readings are outdated (which we received tons of feedback on the delivery side) - they should be reviewed for each release.

**Comment by Chianti7** [comment]
Spelling and grammar check completed.

**Comment by cruzaprild** [comment]
Moving to done.
