### ISSUE TITLE
Self-Paced Learning: R1A - Digital Services – The Who and The What

### ISSUE THREAD

**Issue by cruzaprild** [usds/ditap-curriculum-update#156]
**Ticket Verifier**: Teresa

**Dependencies**
- None

**Definition of success**
- "Required readings" have been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS. 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)
- View LMS tab for more information

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by teresahernandezidt** [comment]
Starting Curriculum Design Audit

**Comment by teresahernandezidt** [comment]
Reassigning for Spelling and Grammar and Curriculum Design

**Comment by teresahernandezidt** [comment]
Curriculum Design complete

**Comment by cruzaprild** [comment]
Assigning for remaining audits
