### ISSUE TITLE
SBA Case Study: R1 SBA Procurement Case Study Facilitator Notes

### ISSUE THREAD

**Issue by teresahernandezidt** [usds/ditap-curriculum-update#157]
**Verifier:** @Chianti7 

**Dependencies**
- None

**Definition of success**
- [Case Study Facilitator Notes](https://docs.google.com/document/d/1UQs3DhM9WPhhIUYehqnn5R56-NJrei-O/edit) has been reviewed using the [audit (rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing))

**Other information**

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by Erin-Murphy-Ei** [comment]
Starting Curriculum Design audit

**Comment by Erin-Murphy-Ei** [comment]
Also doing spelling and grammar at the same time

**Comment by Erin-Murphy-Ei** [comment]
Curriculum Design and Spelling and grammar finished
