### ISSUE TITLE
SBA Case Study: R1 Oral Presentation Instructions

### ISSUE THREAD

**Issue by teresahernandezidt** [usds/ditap-curriculum-update#159]
**Dependencies**
- None

**Definition of success**
- [Oral Presentation Instructions](https://drive.google.com/drive/u/0/folders/1NvlWgFLB8U3Yy6bkz8aJQHej9SbUccI8)] has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [ ] Spelling and grammar
- [ ] Curriculum design
- [ ] Assessments
- [ ] 508 compliance
- [ ] Experiential learning
- [ ] SME audit

**Comment by cruzaprild** [comment]
This ticket is declined and work for it has been captured in https://github.com/usds/ditap-curriculum-update/issues/179.
