### ISSUE TITLE
SME Audit: Activities - R3 Vendor Roundtable Activity

### ISSUE THREAD

**Issue by teresahernandezidt** [usds/ditap-curriculum-update#163]
**Dependencies**
- None

**Definition of success**
- [[Vendor Roundtable Activity](https://docs.google.com/document/d/1MtkxvtEGg3fn3yP10EGtC2KmC7arRXGR/edit)] has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by kathryn-mullins-tandem** [comment]
Review completed, like the structure, approach,a nd format for this activity, feels like a good one to hold onto in the redesign, and improve!
