### ISSUE TITLE
Self-Paced Learning: R1A - Defining Your Role and Your Agency Team Member's Roles as Digital Services Acquisition Professionals

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#168]
**Dependencies**
- None

**Definition of success**
- Defining Your Role and Your Agency Team Member's Roles as Digital Services Acquisition Professionals has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS. 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) - View LMS tab for more information

- [x] Spelling and grammar
- [x] Curriculum design
- [ ] 508 compliance

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Design

**Comment by teresahernandezidt** [comment]
Curriculum Design audit complete

**Comment by Chianti7** [comment]
Assigning for Spelling and Grammar

**Comment by cruzaprild** [comment]
Assigning for 508 compliance

**Comment by cruzaprild** [comment]
All audits complete. Marking done.
