### ISSUE TITLE
Self-Paced Learning: R1A - Digital Services Blog Activity

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#170]
**Dependencies**
- None

**Definition of success**
- Digital Services Blog Activity has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS.

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) - View LMS tab for more information

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by cruzaprild** [comment]
@Erin-Murphy-Ei Per our discussion, I'm assigning you a few self-paced learning tickets to do the curriculum design audit for. Our target completion date is 11/26 (end of sprint 2). Let me know if you have any questions!

**Comment by Erin-Murphy-Ei** [comment]
spelling and grammar and CD in process

**Comment by Erin-Murphy-Ei** [comment]
S&G and CD complete
