### ISSUE TITLE
Self-Paced Learning: R1B - Understanding Sources of Supply

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#173]
**Dependencies**
- None

**Definition of success**
- Release 1.B Understanding Sources of Supply has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS.

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) - View LMS tab for more information

- [ ] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by cruzaprild** [comment]
@Erin-Murphy-Ei Per our discussion, I'm assigning you a few self-paced learning tickets to do the curriculum design audit for. Our target completion date is 11/26 (end of sprint 2). Let me know if you have any questions!

**Comment by april-cruz** [comment]
Unassigning this task and putting it back in the queue for anyone to pick up.

**Comment by Chianti7** [comment]
Picking up for CD

**Comment by teresahernandezidt** [comment]
assigning for Curriculum Audit

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete

**Comment by kristenjernigan** [comment]
Starting 508 audit

**Comment by kristenjernigan** [comment]
508 audit complete

Starting spelling/grammar audit

**Comment by kristenjernigan** [comment]
Spelling/grammar audit complete.
