### ISSUE TITLE
SME Audit: R1 SBA Case Studies 

### ISSUE THREAD

**Issue by teresahernandezidt** [usds/ditap-curriculum-update#179]
**Dependencies**
- None

**Definition of success**
- Case studies have been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)
- Notes are added to the ticket about which case studies could be used in future and which can be discarded.

**Other information**
Updated 12/9:
- This review is a MEDIUM PRIORITY task. No in-depth look is required. The case studies listed below are ones from the original curriculum. There are new case studies that will be replacing these. The purpose of this review is to assess the following:

Are any of the original case studies worth keeping based on relevancy?

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [ ] SBA Case Study: R1 US Digital Service Discovery Sprint Part 2
- [ ] SBA Case Study: R1 Statement of Objectives
- [ ] SBA Case Study: R1 Oral Presentation Instructions
- [ ] SBA Case Study: R1 Backlog Items (Appendix A)
- [ ] SBA Case Study: R1 Instructions, Conditions, and Notices to Offerors
- [ ] US Digital Service Discovery Sprint Part 1
- [ ] US Digital Service Discovery Sprint Part 2
- [ ] SBA Case Study: R1 SBA Procurement Case Study Facilitator Notes ([This ticket was completed here](https://github.com/usds/ditap-curriculum-update/issues/157))

**Comment by bevasq** [comment]
@vdavez could you kindly audit this? Thank you.

**Comment by bevasq** [comment]
Audit complete
