### ISSUE TITLE
Self-Paced Learning: R2A - Activity: Change Readiness Survey

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#182]
**Dependencies**
- None

**Definition of success**
- Activity: Change Readiness Survey has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS. https://ditap.learning-transformation.com/courses/course-v1:ICF+DITAP01+2018_T1/course/

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)  View LMS tab for more information

- [x] Spelling and grammar
- [x] Curriculum design
- [x] 508 compliance

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete

**Comment by teresahernandezidt** [comment]
Assinging for Spelling/Grammar

**Comment by kristenjernigan** [comment]
Starting 508 audit.

**Comment by kristenjernigan** [comment]
508 audit complete.

**Comment by teresahernandezidt** [comment]
Spelling and grammar complete
