### ISSUE TITLE
Self-Paced Learning: R2B - Release 2 Classroom Materials

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#191]
**Dependencies**
- None

**Definition of success**
- Release 2 Classroom Materials has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS.
- Slides mentioned at top of page should have been audited during the Content Map/In class sessions stage of the audit

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) View LMS tab for more information

- [ ] Spelling and grammar
- [x] Curriculum design
- [ ] 508 compliance

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Audit

**Comment by teresahernandezidt** [comment]
Curriculum Audit is complete

**Comment by teresahernandezidt** [comment]
assigning for Spelling/Grammar

**Comment by kristenjernigan** [comment]
@teresahernandezidt Apologies, I started the spelling/grammar audit without commenting.  That is now complete. 

508 audit complete as well.
