### ISSUE TITLE
Self-Paced Learning: R3A - Online Learning: The Acquisition Strategy

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#195]
**Dependencies**
- None

**Definition of success**
- Online Learning: The Acquisition Strategy has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS.

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) View LMS tab for more information 

- [x] Curriculum design

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Audit

**Comment by teresahernandezidt** [comment]
Curriculum Audit Complete

**Comment by april-cruz** [comment]
@TahiraG @teresahernandezidt I am marking this as done since it looks like Teresa completed the audit on it.
