### ISSUE TITLE
SME Audit: Self-Paced Learning - R3A Activities 

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#196]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleN

- [ ] Activity: Developing the Acquisition Strategy
- [ ] Activity: FedRAMP and Digital Services
- [ ] MAP Case Study: Developing the RFQ - Part I

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS.

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) View LMS tab for more information 

This is a HIGH PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
Audit complete
