### ISSUE TITLE
Self-Paced Learning: R3A - Activity: Developing the Acquisition Strategy

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#197]
**Dependencies**
- None

**Definition of success**
- Activity: Developing the Acquisition Strategy has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- Auditor will need to log into the ICF site to view this content in the LMS.

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) View LMS tab for more information 

- [ ] Spelling and grammar
- [ ] Curriculum design
- [ ] Assessments
- [ ] 508 compliance
- [ ] Experiential learning
- [ ] SME audit

**Comment by cruzaprild** [comment]
Declined and wrapped up in ticket https://github.com/orgs/usds/projects/263/views/13?visibleFields=%5B%22Title%22%2C%22Status%22%2C138871328%2C144744413%2C138871331%2C%22Assignees%22%5D&filterQuery=label%3Aaudit&pane=issue&itemId=86263339&issue=usds%7Cditap-curriculum-update%7C196
