### ISSUE TITLE
Create AUTHORS.txt, CONTRIBUTING.md, CONTRIBUTORS.txt

### ISSUE THREAD

**Issue by mgifford** [usds/ditap-curriculum-update#2]
These files can help to guide the contribution process and make sure that ownership and attribution issues are addressed.

**Comment by farooqzakhilwal** [comment]
@mgifford This looks great! 

@frank-mcnally I am wondering if we should start pulling in DPG language at this stage? You can review the file here: 
https://github.com/usds/ditap-curriculum-update/blob/main/CONTRIBUTING.md
