### ISSUE TITLE
SME Audit: Release 1 Materials - Slides

### ISSUE THREAD

**Issue by ghost** [usds/ditap-curriculum-update#223]
**Dependencies**
- None

**Definition of success**
- Release 1 Slides have been reviewed per Assessment and SME audit tabs of audit rubric. (https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

- [ ] Slides R1 (Day 1)
- [ ] Slides R1 (Day 2)
- [ ] Slides R1 (Day 3)

**Other information**
- 

**Additional context**
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 1. 
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by april-cruz** [comment]
Note that this ticket is LOW PRIORITY. Please see SME Audit DoD spreadsheet for more details.

**Comment by mgifford** [comment]
We've talked about the 508 Compliance/Accessibility section

**Comment by mgifford** [comment]
I've looked at https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?gid=133685746#gid=133685746
