### ISSUE TITLE
SME Audit: Release 1 Materials - Activities

### ISSUE THREAD

**Issue by ghost** [usds/ditap-curriculum-update#225]
**Dependencies**
- None

**Definition of success**
- Release 1 Activities have been reviewed per Assessment and SME audit tabs of audit rubric. (https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

- [ ] >SBA Procurement Case Study Facilitator Notes
- [ ] >Statement of Objectives
- [ ] >Oral Presentation Instructions
- [ ]  >Backlog Items (Appendix A)
- [ ] >Instructions, Conditions, and Notices to Offerors
- [ ]  >US Digital Service Discovery Sprint Part 1
- [ ] >US Digital Service Discovery Sprint Part 2

**Other information**
- 

**Additional context**
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 1. 
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by april-cruz** [comment]
Declined. Creating a new ticket to address this work.
