### ISSUE TITLE
SME Audit: Release 2 Materials - Participant Packet

### ISSUE THREAD

**Issue by ghost** [usds/ditap-curriculum-update#226]
**Dependencies**
- None

**Definition of success**
- Release 1 participant packet has been reviewed per Assessment and SME audit tabs of audit rubric. (https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

- [ ] Participant Packet

**Other information**
- 

**Additional context**
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 1. 
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by april-cruz** [comment]
This is a LOW PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by april-cruz** [comment]
Declined. This task is no longer required.

**Comment by bevasq** [comment]
@april-cruz is there a way to remove these that are no longer valid? I was going through the dashboard and may have assigned these when they are possibly duplicated?

**Comment by april-cruz** [comment]
@bevasq I'm going to see if I can delete them to avoid any future confusion.
