### ISSUE TITLE
SME Audit: Release 3 Materials - Slides 

### ISSUE THREAD

**Issue by ghost** [usds/ditap-curriculum-update#229]
**Dependencies**
- None

**Definition of success**
- Release 3 Slides have been reviewed per Assessment and SME audit tabs of audit rubric. 

[DITAP Refresh Content Audit Release 3 - Google Sheets](https://docs.google.com/spreadsheets/d/1c87nkub-cBbmR-Q-gFa00NZk30Sh1_xBWqo2r50uh8U/edit?gid=898574372#gid=898574372)

- [ ] Cloud Presentation
- [ ] Slides R3 (Day 2)
- [ ] Slides R3 (Day 3)
- [ ] Slides R3 (Day 4)
- [ ] Slides R3 (Day 5)

**Other information**
- 

**Additional context**
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 3. 
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by bevasq** [comment]
@bevasq completed SME audit for these items 11/22

**Comment by cruzaprild** [comment]
@bevasq I know you mentioned on Tuesday that this task would be closed out by COB. I'm going to go ahead and mark it done. (If that is incorrect, just let me know.) Thanks!

**Comment by april-cruz** [comment]
Per discussion at sprint planning, this task is complete.
