### ISSUE TITLE
WS2 Discovery: Prepare to have WS2 test interview with Chianti

### ISSUE THREAD

**Issue by bevasq** [usds/ditap-curriculum-update#234]
**Objective**
- Prepare for first WS2 test interview with Chianti as first interviewee

**Open Questions**
- TBD

**Approach**
- Prepare interview questions, test cases and approach for first interview

**Outcome**
- Conduct initial interview, obtain feedback for improvements/adjustments before scheduling additional interviews.

**Additional Information**

**Comment by bevasq** [comment]
@bevasq will reach out to @Chianti7 to request potential meeting times to discuss interview questions vs survey approach as discuss with @kellysmith1008 and @kathryn-mullins-tandem

**Comment by bevasq** [comment]
Linked with #238

**Comment by bevasq** [comment]
Meeting scheduled with Chianti, Farooq, April and Kelly on 11/26.

**Comment by cruzaprild** [comment]
@bevasq I believe this task is ready to close now and does not need to move to the next sprint. If so, can you mark this task as done? Thanks!

**Comment by bevasq** [comment]
Closed as this task is done.
