### ISSUE TITLE
Discovery: LiaScript research - document findings

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#235]
**Objective**
-  To document LiaScript findings in a report for stakeholders and receive signoff from client stakeholders

**Open Questions**

**Approach**

**Outcome**
- Document findings in a report for stakeholders
- Sign off from client/stakeholders

**Additional Information**

**Comment by cruzaprild** [comment]
@bobschmitt-civicactions Tagging you here as you will be interested in the documentation from this ticket.

**Comment by kristenjernigan** [comment]
[LiaScript findings documentation.docx](https://github.com/user-attachments/files/18085429/LiaScript.findings.documentation.docx)
