### ISSUE TITLE
WS2 Discovery: Connect with Kelly to prepare for interviews and alignment with WS1

### ISSUE THREAD

**Issue by bevasq** [usds/ditap-curriculum-update#238]
**Objective**
- Connect with Kelly to prepare for interviews and alignment with WS1

**Open Questions**
- What is the best way to align with Workstream 1 objectives? 
- What is the best way to approach interview planning? 
- What are the roles & responsibilities?

**Approach**
- TBD

**Outcome**
- Interview plan for WS2 objectives are aligned with WS1

**Additional Information**

**Comment by bevasq** [comment]
Meeting scheduled for 11/20

**Comment by kellysmith1008** [comment]
Hey y'all! Here are the resources we chatted about today in the meeting - please let me know if you need anything else or want to meet again - and I'm excited for the interviews to start! 

[WS 1 draft survey questions](https://docs.google.com/document/d/1ITGJVF2haFecrczaYLndMbd6f2Q1SHqu1wh6-9ExR_M/edit?usp=sharing) (please note some of the questions will change based on feedback in the comments)
[Survey research](https://docs.google.com/document/d/1RwTV2PCrAauDhVNyevUlOgfB2A6MFciiPNhHLQNvjgs/edit?usp=sharing)
[Mural for feedback](https://app.mural.co/t/civicactions3117/m/civicactions3117/1731592648508/ec680f09277b6f316275982e1e930323eb1cc7ab)

**Comment by bevasq** [comment]
Met with @kellysmith1008 (thank you!) who shared very helpful information and guidance. Will review the content Kelly linked above and to prepare for meeting with @Chianti7 next. This item to be closed.
