### ISSUE TITLE
Additional Facilitation Material: R4

### ISSUE THREAD

**Issue by ghost** [usds/ditap-curriculum-update#252]
**Dependencies**
- None

**Definition of success**
- ALL R4 Additional Facilitation Materials (Listed as bullets 1-5 below) have been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

_1. Outline 4.A
2. Iteration Planning Meeting 4.A
3. Outline 4.B
4. Release 4 Assessments Summary Results_

**Other information**
- 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [ ] Spelling and grammar
- [x] Curriculum design
- [ ] 508 compliance

**Comment by kristenjernigan** [comment]
Starting curriculum audit

**Comment by kristenjernigan** [comment]
Curriculum audit complete.
