### ISSUE TITLE
Self-Paced Learning: R5A: Preparing for and Having an Influence Conversation

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#259]
**Dependencies**
- None

**Definition of success**
- Preparing for and Having an Influence Conversation has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Other information**
- **Auditor will need to review Release 5A/5B materials in Google Drive** [Preparing for and Having an Influence Conversation](https://drive.google.com/file/d/1-eeAtHjD-5vI2sVjy8Sd1YZrKCIJiNZ0/view?usp=drive_link)

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0) View LMS tab for more information

- [x] Curriculum design

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete
