### ISSUE TITLE
SME Audit: Release 2 Materials - Slides

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#280]
Dependencies

None
Definition of success

Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] Slides R1 (Day 2)
- [ ] Slides R1 (Day 3)
- [ ] Slides R1 (Day 4)
- [ ] Slides R1 (Day 5)

Other information
This is LOW priority

Additional context
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 2.
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by bevasq** [comment]
Audit complete
