### ISSUE TITLE
SME Audit: Release 4 - Participation Packet

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#282]
**Dependencies**

None

**Notes:**
This is a MEDIUM PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Definition of success**

Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] Participant Packet

**Additional context**
Links to the content materials can be accessed at the content map below until In-Class sessions, Session 4.
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by bevasq** [comment]
Audit complete
