### ISSUE TITLE
SME Audit: Additional Facilitation Materials Release 4 - Outlines

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#286]
**Dependencies**
- None

**Definition of success**
Please add comments to SME audit tab of the following spreadsheet for Release 3: https://docs.google.com/spreadsheets/d/1c87nkub-cBbmR-Q-gFa00NZk30Sh1_xBWqo2r50uh8U/edit?gid=883259296#gid=883259296

Iteration 4.A
- [ ] Outline - https://docs.google.com/document/d/1ibFO7wEFoSrdhLplxSZ-L1M_h1tURPp4/edit

Iteration 4.B
- [ ] Outline - https://docs.google.com/document/d/1E7pCxflEEZtRR33LdM5CUlhc38BLCEPz/edit

This is a LOW PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by mgifford** [comment]
@april-cruz I need more guidance here.

**Comment by april-cruz** [comment]
After further discussion, this ticket will be declined.

**Comment by farooqzakhilwal** [comment]
The Spreadsheet links to Release 3, but materials are for Release 4. 

Noting that these documents were also reviewed by curriculum designers.

**Comment by farooqzakhilwal** [comment]
Done and updated notes.
