### ISSUE TITLE
SME Audit: Threaded Scenarios - MAP Case Study

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#288]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [ ] Threaded scenario text
- [ ] MAP Case Study: Developing the RFP - Part 1
- [ ] Activity: Blog Your Acquisition Package

This is a MEDIUM PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
@vdavez could you please audit this item?

**Comment by bevasq** [comment]
@april-cruz Dave added a comment into the spreadsheet last week and we need some additional information as this information was likely already covered. Could you please advise? Thank you.

**Comment by bevasq** [comment]
@april-cruz I am going to close this as a duplicate. If you disagree, please open again. Thank you!
