### ISSUE TITLE
SME Audit: Self-Paced Learning Iteration 3A - Compliance and other Legal Issues

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#292]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] Online Learning: Compliance & Other Legal Issues
- [ ] Compliance & Other Legal Issues
- [ ] What is Intellectual Property?
- [ ] Types of IP
- [ ] FAR Subpart 27.4 Rights in Data and Copyrights
- [ ] Contribution, Attribution, Retribution…Oh My!
- [ ] Who Owns Open Source Code?
- [ ] Data in the Cloud (It’s Cloudy Out There!)
- [ ] Legal Liabilities
- [ ] What Happens When Open Source Software Breaks?
- [ ] Getting to Know Your Office of General Counsel
- [ ] Knowledge Checks

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

This is a HIGH PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
Audit complete
