### ISSUE TITLE
SME Audit: Self Paced Learning - Iteration 3.A: Developing an Acquisition Strategy - Readings

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#294]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] Readings

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

This is a HIGH PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
Auditi complete
