### ISSUE TITLE
SME Audit: Self-paced learning - Iteration 4.A: Awarding Digital Service Contracts - Online Learning (Technical Evaluation)

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#298]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] --Online Learning: The Technical Evaluation Team
- [ ] --The Technical Evaluation Team
- [ ] --Building a Cross-Functional Team
- [ ] --Preparing the Team
- [ ] --Technical Evaluation Panel Challenges
- [ ] Activity: Tech Evaluation Panel Checklist
- [ ] Activity: The Tradeoff Game
- [ ] Online Learning: Negotiating with Vendors
- [ ] --Introduction
- [ ] --Negotiations: The Basics
- [ ] --Key Strategies for Successful Negotiations with Vendors
- [ ] --Conclusion
- [ ] --Knowledge Checks

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

This is a HIGH PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
@vdavez would you kindly audit this item?
