### ISSUE TITLE
Create LICENSE.md document

### ISSUE THREAD

**Issue by mgifford** [usds/ditap-curriculum-update#3]
We will want to make sure the project aligns with https://www.usa.gov/government-copyright

**Comment by mgifford** [comment]
Just added here https://github.com/usds/ditap-curriculum-update/blob/main/LICENSE.md

**Comment by farooqzakhilwal** [comment]
@frank-mcnally this is ready for your review. Link above.

**Comment by frank-mcnally** [comment]
I'm not a copyright expert, but this is clear and readable and makes sense to me. Per Mike's note in the description, we want to make sure it does align with any existing USG copyright guidance. Is this something we need further approval (e.g., OMB counsel)?

**Comment by mgifford** [comment]
@frank-mcnally I'm not a copyright expert, but I think this complies.  There's no harm asking for legal advice from the OMB but it is unlikely that they will advise much different. I'll reach out to our general counsel to see if there is any different advice.

**Comment by cruzaprild** [comment]
@mgifford Did you hear anything back from general counsel? I'm looking to close this ticket out if there isn't more to discuss. Thanks!
