### ISSUE TITLE
SME Audit: Self-Paced learning - Iteration 1A: The Digital Services Professional -  Defining your role

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#303]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] --Online Learning: Defining Your Role and Agency Team Member's Roles as Digital Services Acquisition Professionals (Required)
- [ ] --Defining Your Role and Your Agency Team Member's Roles as Digital Services Acquisition Professionals
- [ ] --What is a Change Ambassador?
- [ ] --What is Influence? Why is it Important in Digital Services Acquisition and Leadership?
- [ ] --Sphere of Influence and the Six Degrees of Kevin Bacon
- [ ] --Steps in Using Your Sphere of Influence
- [ ] --Issues in Creating Influence: The Impact of Power Relationships on Your Ability to Influence
- [ ] --Issues in Creating Influence: Building Your Network
- [ ] --Completion Check

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

This is a MEDIUM PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
Audit complete.
