### ISSUE TITLE
SME Audit: Iteration 2.A: Understanding Your needs and Agency Readiness - Tech Far Hub Activity

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#304]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] Activity: Determine Your Organizational Readiness on TechFAR Hub

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

This is a MEDIUM PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by bevasq** [comment]
Audit complete
