### ISSUE TITLE
SME Audit: Iteration 1A: The Digital Services Professional - Online Learning: Digital Services - The Who & What (B)

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#306]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [x] --Digital Services – The Who and The What
- [x] --Then and Now: USCIS.gov Use Case
- [ ] --Defining Digital Services: Another Take
- [ ] --Let's Check Your Knowledge (1)
- [ ] --The Digital Services Ecosystem
- [ ] --The Digital Services Ecosystem, Part 2
- [ ] --Let's Check Your Knowledge (2)
- [ ] --Who’s Who: Finding and Following Leaders in Digital Services
- [ ] --Who’s Who: A Starting List
- [ ] --Completion Check

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by mgifford** [comment]
I think I've gone through this, but they aren't all in separate rows.
