### ISSUE TITLE
Add Additional Facilitation Materials directory and artifacts to GitHub

### ISSUE THREAD

**Issue by bobschmitt-civicactions** [usds/ditap-curriculum-update#307]
Add Additional Facilitation Materials directory and artifacts to GitHub
Item status based on EdX overview document.

**Comment by april-cruz** [comment]
@bobschmitt-civicactions Can this task be closed today? I know this was part of what you were demo'ing to me earlier. Today is the last day of the sprint.

**Comment by bobschmitt-civicactions** [comment]
@april-cruz You can move this to the next sprint.

**Comment by bobschmitt-civicactions** [comment]
@farooqzakhilwal Can you review this PR? https://github.com/usds/ditap-curriculum-update/pull/322

**Comment by bobschmitt-civicactions** [comment]
Branch merged. Closing this ticket.
