### ISSUE TITLE
Digital Services Acquisition Expert Facilitator Presentations

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#310]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

- [ ] Implementing agile in government 

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [x] Curriculum design

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete
