### ISSUE TITLE
Live Digital Assignments and final presentation - Releases 1, 2, 4, and 4

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#311]
**Dependencies**
- None

**Definition of success**
All content (checkboxes below) has bee reviewed and comments added to rubric spreadsheet for Release 1:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

Please consider the following in comments:
Can live digital assignments correspond with case studies?

Release 1
- [x] >Link to edX Iteration 1.A > Live Digital Assignment: Task 1
- [x] >Link to edX Iteration 1.B > Live Digital Assignment
Release 2
- [x] >Link to edX Iteration 2.A > Live Digital Assignment: Develop The Product Vision
- [x] >Link to edX Iteration 2.B > Live Digital Assignment: Develop The Product Vision
Release 3
- [x] Demo Day 1
- [x] >Link to edX Iteration 3.A > Live Digital Assignment: Developing a Plan for How to Test
- [x] >Link to edX Iteration 3.B > Live Digital Assignment: Complete the Plan
- [x] Demo Day 2
Release 4
- [x] Link to edX Iteration 4.A>Testing your Hypothesis
- [x] -Final Presentation Example

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [x] Curriculum design

**Comment by TahiraG** [comment]
Currently reviewing new case studies.

**Comment by TahiraG** [comment]
Pausing review of Case Studies
__Farooq
on a chat with Becky earlier, she mentioned that For #311, TandemGov has already seen the case study. There likely isn’t a need for a curriculum designer to review as well.
:ty:
1_

Tahira
This is something I mentioned to 
[@April]
 before moving through the ticket (that is would require review of the Case Studies). The expectation was that they be reviewed by both. At this point, I have reviewed 3 of the 5, but happy to pause._

**Comment by TahiraG** [comment]
Ready for review @april-cruz. :-)

**Comment by april-cruz** [comment]
Thank you for adding your notes here. Did a review and am moving to done now!
