### ISSUE TITLE
Orientation Materials (Overall Grades)

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#314]
**Dependencies**
- None

**Definition of success**
Content has bee reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

Auditors can log comments in the Release 1 Audit Rubric spreadsheet. 

- [x] >Capstone Results Summary
- [x] >Live Digital Assignment Summary
- [x] >Live Digital Assignment Final Scores
- [x] >Participant Grade Tracking
- [x] >Final Participant Scores

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [x] Curriculum design

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Audit

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete
