### ISSUE TITLE
Orientation Materials (Facilitator Skill Sets and Estimated Level of Effort)

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#315]
**Dependencies**
- None

**Definition of success**
- [Content type] has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

Auditor can log comments in release 1 spreadsheet. 

- [ ] - [ ] Facilitator Skill Sets and Estimated Level of Effort

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [ ] Curriculum design

**Comment by april-cruz** [comment]
@Chianti7 I'm going to go ahead and move this to sprint 4.

**Comment by Chianti7** [comment]
@april-cruz  Thanks! 

Assigning for Curriculum Design
