### ISSUE TITLE
In class Sessions: Release 4 - Assessments

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#317]
**Dependencies**
- None

**Definition of success**
[- [Content type] has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)](https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R)

Auditor can log comments to release 1 spreadsheet.
- [x] Rating Form for Guest Panel
- [x] Rating Form for Participants

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [x] Curriculum design

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Audit

**Comment by teresahernandezidt** [comment]
Curriculum Audit complete

**Comment by april-cruz** [comment]
Marking as done.
