### ISSUE TITLE
Course-Level Assessments: IDP Start of Program and IDP Iteration Level Feedback

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#319]
**Dependencies**
- None

**Definition of success**

IDP Start of Program AND IDP Iteraiton Level Feedback has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

- [ ] Curriculum design

**Comment by teresahernandezidt** [comment]
Assigning for Curriculum Audit

**Comment by Chianti7** [comment]
Curriculum Design Complete
