### ISSUE TITLE
SME Audit: In-Class Sessions: Release 3 - iteration 3.A and 3.B Outlines

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#324]
**Dependencies**
- None

**Definition of success**
Content has been reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

Auditor should log comments in release 3 rubric.

**Iteration 3.A**

- [x] >Outline

**Iteration 3.B**

- [x] >Outline

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by mgifford** [comment]
@april-cruz I'm not sure what to do here.

**Comment by april-cruz** [comment]
After further discussion, this ticket will be declined.

**Comment by farooqzakhilwal** [comment]
Done. Spreadsheet updated.
