### ISSUE TITLE
SME Audit: In-Class Sessions: Release 2 - iteration 2.A and 2.B Outlines

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#325]
**Dependencies**
- None

Dependencies

None
Definition of success
Content has been reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

Auditor should log comments in release 2 rubric. 

Iteration 2.A
>Outline

Iteration 2.B
>Outline

Additional context
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by mgifford** [comment]
Am I supposed to look at https://docs.google.com/spreadsheets/d/1W04Dq5MrsxV0kd6SQkeBiA_FoNfy7HrCBRXYQ7VIJkw/edit?gid=1090246143#gid=1090246143

I don't know @april-cruz

**Comment by april-cruz** [comment]
After further discussion, this ticket will be declined.

**Comment by farooqzakhilwal** [comment]
Complete. Moving to done. Also noting that reviewing reviewing these outlines could all have been 1 ticket. I have done 3, and they all have the same issues so my comments for them are exactly the same.
