### ISSUE TITLE
SME Audit: Self Paced Learning: Iteration 1A: The Digital Services Professional - Online learning

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#326]
**Dependencies**
None

**Definition of success**
Content has been reviewed according to rubric:
Rubric Folder: https://drive.google.com/drive/folders/1Sg1dZyl7d1Ir3lBImydJlHeCaKleNX9R

Auditor can log comments in release 1 rubric.

- [x] --Online Learning: Digital Services - The How (Required)
- [x] --Digital Services – The How
- [x] --Learn About Your Users’ Needs
- [x] --Learn About Your Users’ Needs Cont'd
- [x] --Contemporary Practices in Developing Digital Services
- [x] --Contemporary Practices Cont'd: DevOps, Modern Technology Stacks, Open Source
- [x] --Contemporary Practices Cont'd: Open Data and the Cloud
- [x] --Connecting the Dots
- [ ] --Completion Check

</google-sheets-html-origin>

Outline
Additional context
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

This is a LOW PRIORITY task. See SME Audit DoD spreadsheet for more details.

**Comment by mgifford** [comment]
Ok, I've gone through and added the notes in the spreadsheet.
