### ISSUE TITLE
SME Audit: Iteration 1B - Digital Services World - Online learning (sources and supply) and activity

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#331]
**Dependencies**
- None

**Definition of success**
- [Content type] has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

Auditor should log comments in release 1 audit spreadsheet. 

- [x] --Online Learning: Understanding Sources of Supply
- [x] --Understanding Sources of Supply for Digital Services
- [x] --Marketplace Segment: Cloud Services
- [x] --Marketplace Segment: Software Development
- [x] --Marketplace Segment: Cloud Service (XaaS)
- [x] --Marketplace Segment: Cloud Service (XaaS), part 2
- [x] --Marketplace Segment: Cloud Service (XaaS), part 3
- [x] --Marketplace Segment: Open Source Software
- [x] --Marketplace Segment: Design Services
- [x] --Marketplace Segment: Big Data and Open Data
- [x] --Sources of Supply: The Suppliers
- [x] --Sources of Supply: Contractual Vehicles
- [x] --Knowledge Check
- [x] --Completion Check
- [x] Activity: Trend Analysis of Fast Company's Most Innovative Companies

**Additional context**
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by april-cruz** [comment]
After further discussion, this ticket will be declined.

**Comment by farooqzakhilwal** [comment]
done
