### ISSUE TITLE
SME Audit: Iteration 1B - Digital Services World - Online learning (agile), Introduction and Readings

### ISSUE THREAD

**Issue by april-cruz** [usds/ditap-curriculum-update#332]
**Dependencies**
None

**Definition of success**

[Content type] has been reviewed using the [audit rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)

Auditor should log comments in release 1 audit spreadsheet.

Online Learnings
- [x] --Online Learning: Agile Methodologies
- [x] --Introduction
- [x] --Kanban vs Scrum
- [x] --Measurement and the Modern Family of Technologies
- [x] --Completion Check

Readings

- [x] Introduction
- [x] Readings

Additional context
[Content Map](https://docs.google.com/spreadsheets/d/1kpNHBFV-v6RCWhLeIFkMvbbRR5e8t2dbtqlvnbwuevQ/edit?gid=0#gid=0)

**Comment by april-cruz** [comment]
After further discussion, this ticket will be declined.

**Comment by april-cruz** [comment]
After further discussion, this ticket will be declined.

**Comment by farooqzakhilwal** [comment]
Done.
