### ISSUE TITLE
Define Audit Process

### ISSUE THREAD

**Issue by kellysmith1008** [usds/ditap-curriculum-update#55]
**Dependencies**

- Completion of audit rubric (#54 )
- Review audit rubric
- Team members know their role for the audit (completed in #69 )

**Definition of Success**

- Team understands the audit process
- We have a clearly defined instructions for the process of auditing 60%
- We have a spreadsheet to track the audit 

**Open questions**

- Is this spreadsheet the same as the rubric spreadsheet or a different one? 
- Could this be a consideration for contribution to TechFAR Hub?

**Comment by Chianti7** [comment]
@kellysmith1008 I'd love to cowork on this item and also because of her expertise would like to invite @teresahernandezidt to cowork on it as

**Comment by teresahernandezidt** [comment]
@Chianti7 and I synced earlier today (10/22) to discuss the Audit Process. The [documentation](https://docs.google.com/document/d/1M7gnkv81atQULfFWjRTs7EFixw_dqTuYg1pWy5PhW94/edit?usp=sharing) from our conversation is included here.

**Comment by kellysmith1008** [comment]
@teresahernandezidt and I met today to talk about the rubric and how the roles could be defined as part of my ticket #69. 
[Link to the rubric](https://docs.google.com/spreadsheets/d/15ryjqGEn9NCMztE0RjSYvNHlwWxCiU3MPUL3rCr3L3g/edit?usp=sharing)
[Link to the google form for roles and audit responsibilities](https://forms.gle/vUoQXGHdHeeNr4Mz8)

**Comment by Chianti7** [comment]
@cruzaprild We added a reference to the Learning Design Document in the audit process. The hyperlink will need to be added to all of the created issues/tickets related to the audit. Should this be a sprint planning task? 

Here is the link: https://docs.google.com/spreadsheets/d/1lj9QHErQN9LlltA34IcMTRp2MKUMPMlv/edit?gid=165337120#gid=165337120

**Comment by cruzaprild** [comment]
Does it make sense for this to be added to the additional info/context sections of all of the tickets? I think I can just add it to all of the tickets. How should people interact with the LDD doc as they do the audit?

**Comment by Chianti7** [comment]
@cruzaprild I think you can add it to all the tix in additional info. Also, the notion of the LDD being referenced was influenced by @farooqzakhilwal's note in Slack about should the LDD be used as we audit. I think for anyone who is taking on the Curriculum Designer lens as they audit  the answer is - yes. @teresahernandezidt and I viewed it yesterday and it's the source doc that houses all of the learning objectives for the program. @TahiraG do you have any thoughts on this?

**Comment by teresahernandezidt** [comment]
The [Audit Process document](https://docs.google.com/document/d/1M7gnkv81atQULfFWjRTs7EFixw_dqTuYg1pWy5PhW94/edit?tab=t.0) is being posted here for our discussion for Monday's scrum meeting.

**Comment by kathryn-mullins-tandem** [comment]
Hi all....quick question....is it OK for me to add a new tab to the Content Audit Release 1 spreadsheet to capture a new structure/ recommendations to update the SME audit tab? @teresahernandezidt

**Comment by teresahernandezidt** [comment]
Hello @kathryn-mullins-tandem! If possible, please feel free to make these updates/recommendations to the SME audit tab itself. You are more than welcome to include a comment for context. Please also feel free to highlight any new columns to draw attention to any new updates. Thank you for your feedback!

**Comment by Chianti7** [comment]
Decision made on 11/5 to remove "experiential tab" from the Audit Rubric. The criteria for the experiential lens will be folded into the Curriculum Design tab of the rubric. 

@teresahernandezidt Will update the template and other releases. 

@Erin-Murphy-Ei will share additional criteria to add to the Curriculum Design tab to to ensure it's reflected for the experiential lens of the audit. 

cc: @cruzaprild

**Comment by cruzaprild** [comment]
@Chianti7 @teresahernandezidt Can this task be closed out now?

**Comment by Chianti7** [comment]
@cruzaprild I would say it's ready to be closed.
