### ISSUE TITLE
Transfer DITAP curriculum V1 to Github repo

### ISSUE THREAD

**Issue by kellysmith1008** [usds/ditap-curriculum-update#57]
**Dependencies: (as applicable):**
- Is there any issue with this being done the same time as Google?
- Do we receive the export file?

**Open questions:**
- Who is a good resource to discuss this with? Kristen may have more knowledge of this and answer LOE questions.

**Definition of Success:**
- Transfer DITAP curriculum to GitHub so that V1 is available in the public repo
- Organize content according to how it is structured currently on the site

**Additional information/notes**
- Link to curriculum: https://ditap.learning-transformation.com/courses/course-v1:ICF+DITAP01+2018_T1/f74f6baf4a0d42558c13bd70b76f03e5/#:~:text=The%20following%20content%20map%20contains%20all%20of%20the

**Comment by kellysmith1008** [comment]
If we can't get the information today it may be necessary to pull it down manually

**Comment by april-cruz** [comment]
Declining this ticket. The work is represented in other tickets.
