### ISSUE TITLE
Audit Experiential Learning Approaches

### ISSUE THREAD

**Issue by kellysmith1008** [usds/ditap-curriculum-update#62]
**Dependencies**
-  #55 
-  #54 
- 
**Definition of Success**
- Collected existing experiential learning modules in the course
- Used the audit rubric on each module 
- Decided which modules stay, which go, and which need updating

**Other information**
- Erin from Ei Institute mentioned as a strength for her team

**Comment by cruzaprild** [comment]
Experiential learning audit criteria was added to the curriculum design audit rubric so this ticket is no longer necessary. Marking as declined.
