### ISSUE TITLE
Create quarterly roadmap and goals

### ISSUE THREAD

**Issue by kellysmith1008** [usds/ditap-curriculum-update#64]
Dependencies
-Synthesis from Strategy session 2 #63

Definition of Success
- Develop a quarterly roadmap
- Meet with team to share out roadmap and goals

Other information

**Comment by cruzaprild** [comment]
The roadmaps were created and surfaced to the team to preview and Frank for review. There was no further feedback, so they will be presented at the sprint demo on 10/29.
