### ISSUE TITLE
Discovery: Workstream 2 (DITAP Consortium)

### ISSUE THREAD

**Issue by kristenjernigan** [usds/ditap-curriculum-update#76]
Objective
- Connect with Dave Z and team on initial support for DITAP Consortium work

Open questions
- Is support needed with prioritization of tasks?
- Can we assist with getting tasks into GitHub?
- What are our future needs? 

Approach
- Set up a meeting with Dave Z and team to discuss this work

Outcome
- Documented next steps for Workstream 2 may included stubbing out tickets for project board
- Other follow up tasks

Additional information/notes
- TandemGov is using the following document to outline their approach to the work: https://docs.google.com/document/d/1iv2Vi7kSMVWMwBnzqFA-Da_9XhQM7yjIFR6O2wf6RTg/edit?tab=t.0#heading=h.7zb8qbibmnsr

**Comment by kathryn-mullins-tandem** [comment]
@kristenjernigan glad to catch up, we were actually planning to reach out to @farooqzakhilwal on the same thing! Let us know when you want to find some time; early next week might be best.

**Comment by farooqzakhilwal** [comment]
@kathryn-mullins-tandem I'll reach out to coordinate

**Comment by farooqzakhilwal** [comment]
May be a comment could be:
On 10/23, CA met with Dave, Kathryn and Becky to discuss how we will communicate, collaborate, and use the project board. Meeting notes and action items were documented here: https://docs.google.com/document/d/1RZHovtejf5f780lItuzOb9IIHIAWVXKFQk1EqafvDLo/edit?tab=t.0#heading=h.y1x7em2awrch
